[project]
name = "NeoFOAM"
version = "0.0.1"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/exasim-project/NeoFOAM"
git_default_branch = "main"

[paths]
compile_commands = "build/compile_commands.json"
