name: Build NeoFOAM
run-name: 'Build workflow'

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    types: synchronize
  schedule:
    - cron: "* 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build NeoFOAM
    strategy:
      fail-fast: false
      matrix: 
        compiler: 
          - CC: clang
            CXX: clang
          - CC: gcc
            CXX: g++
    runs-on: ubuntu-latest
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v4

     - name: Install dependencies 
       run: |
         sudo apt update
         sudo apt install \
           ninja-build \
           clang-15 \
           gcc-10 \
           libomp-15-dev \
           python3 \
           python3-dev \
           build-essential  
         sudo apt remove clang-14
         sudo rm /usr/bin/clang
         sudo ln -s /usr/bin/clang-15 /usr/bin/clang


     - name: Get versions
       run: |
         clang --version
         ninja --version
         cmake --version

     - name: Build NeoFOAM
       run: |
         CC=${{matrix.compiler.CC}} \
         CXX=${{matrix.compiler.CXX}} \
         cmake --preset ninja-cpuonly-test
         cmake --build build/ReleaseWithTests
