name: Build NeoFOAM
run-name: 'Build and integration'

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    types: synchronize
  schedule:
    - cron: "* 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: build NeoFOAM
    strategy:
      fail-fast: false
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Install meson
       run: |
        sudo apt install -y python3 python3-pip python3-setuptools python3-wheel ninja-build
     - name: build NeoFOAM
       run: |
         meson setup builddir && cd builddir
         meson compile
         meson test
