name: Build NeoFOAM
run-name: 'Build and integration'

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    types: synchronize
  schedule:
    - cron: "* 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: alpine-latest
    container: greole/neofoam
    name: build NeoFOAM
    strategy:
      fail-fast: false
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3

     - name: Install meson
       run: |
        sudo apt install -y \
          python3 python3-pip python3-setuptools python3-wheel \
          iwyu

     - name: Build NeoFOAM
       run: |
         mkdir build && cd build
         cmake -G Ninja ..
         cmake --build .

     - name: Execute iwyu
       run: |
         iwyu_tool -p builddir || true # don't fail for now
