name: Check clang-tidy
run-name: Check clang-tidy

on: push
jobs:
  clang-tidy-check:
    name: Clang-tidy Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add clang repo
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main'
        wget https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo apt-key add llvm-snapshot.gpg.key

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install \
           ninja-build \
           clang-16 \
           clang-tidy-16 \
           libomp-16-dev

    - name: Create Compilation Database
      run: |
        cmake --preset ninja-cpuonly-all -DNEOFOAM_DEVEL_TOOLS=OFF
    - name: Run clang-tidy
      run: |
         run-clang-tidy-16 -p build/ReleaseAll/ -fix

    - name: Check for fixes
      run: |
        if [[ $(git ls-files -m | wc -l) -eq 0 ]]; then
          exit 0
        fi
        echo "There are fixes available from clang-tidy."
        echo "Please use your local clang-tidy or apply the following patch:"
        git diff -p
        exit 1
