name: Docs

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    types: synchronize
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Requirements
      run: brew install doxygen
        && brew install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
        && pip3 install sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build docs
      run: |
        sphinx-quickstart . -q -p NeoFOAM -a "The NeoFOAM authors" -v "0.0.1" -l "en"
        make html
        pwd
        cd _build/html
        touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _build/html # The folder the action should deploy.
