name: Docs

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    types: synchronize
  
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Requirements
      run: brew install doxygen
        && brew install sphinx-doc
        && pip3 install furo
        && pip3 install breathe
        && pip3 install sphinx-sitemap
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build docs
      run: |
        mkdir build
        cd build
        cmake -DNEOFOAM_BUILD_DOC=On ..
        cmake --build . -t doc
        cp -r docs/doxygen docs/sphinx
        cd docs/sphinx
        touch .nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/docs/sphinx
