name: Test GitHub Action
on: [pull_request]
run-name: Format Check

jobs:
  run:
    name: Format check with foam-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install pip
      run: |
       sudo apt install -y python3 python3-pip python3-setuptools python3-wheel ninja-build
       pip3 install --user meson
    - name: fetch foam-format
      run: |
        git clone https://github.com/exasim-project/foam-format
        cd foam-format
        pip3 install --user .
    - name: Run format check
      run: |
        foam-format --target=src

