name: spdx

on:
  pull_request

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
    - name: install reuse linter 
      run: |
        pip3 install reuse

    - name: Execute reuse linter 
      run: |
        reuse lint
