name: spdx

on:
  pull_request

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: install reuse linter 
        run: |
          pip3 install reuse

      - name: Execute reuse linter 
        run: |
          reuse lint
