name: Build NeoFOAM Windows

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types: synchronize
  schedule:
    - cron: "* 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  windows_mingw:
    if: ${{!contains(github.event.pull_request.labels.*.name, 'Skip-build')}}
    name: mingw/${{ matrix.config.name }}
    runs-on: [windows-latest]
    steps:
    - name: Checkout the latest code (shallow clone)
      uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: configure
      run: |
        cmake --preset develop -DKokkos_DIR="D:/dev/Kokkos/lib/cmake/Kokkos" -DNEOFOAM_DEVEL_TOOLS=OFF -DNEOFOAM_ENABLE_MPI_SUPPORT=OFF
      shell: cmd

    - name: build
      run: |
        set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
        set PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
        set PATH=C:\Program Files (x86)\Ginkgo\bin;%PATH%
        cmake --build --preset develop
      shell: cmd

    - name: test
      run: |
        set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
        set PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
        set PATH=C:\Program Files (x86)\Ginkgo\bin;%PATH%
        cmake --build --preset develop --target test
      shell: cmd
